apiVersion: v1
kind: Secret
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  containers:
    - name: webapp
      image: webapp
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: app-secret
