apiVersion: v1
kind: Pod
metadata:
 name: podman-priv-test
spec:
 containers:
   - name: priv-test
     image: vaishakh183/podman-ubuntu
     args:
       - sleep
       - "1000000"
     securityContext:
       privileged: true
